#!/usr/bin/env bash
# Regenerate lib/db/rds-ca.ts from the published Amazon RDS trust store.
#
#   bash aws/scripts/fetch-rds-ca.sh [region]
#
# Only needed if AWS publishes a new regional root. The current bundle is valid
# to 2121, so this is not a rotation treadmill.
#
# It writes a TypeScript module rather than a .pem because the certificate has
# to survive three different bundlers - the Next standalone build, esbuild for
# the Lambda workers, and plain tsx for the harness - and a string import cannot
# be silently omitted from a bundle the way a file read with `fs` can.
set -euo pipefail
cd "$(dirname "$0")/../.."

REGION="${1:-ap-southeast-1}"
URL="https://truststore.pki.rds.amazonaws.com/${REGION}/${REGION}-bundle.pem"
PEM="aws/certs/${REGION}-bundle.pem"

mkdir -p aws/certs
echo "==> $URL"
curl -fsSL "$URL" -o "$PEM"

count=$(grep -c "BEGIN CERTIFICATE" "$PEM")
[ "$count" -ge 1 ] || { echo "ERROR: no certificates in the downloaded bundle" >&2; exit 1; }
echo "==> $count certificate(s)"

{
  cat <<HDR
// Amazon RDS certificate authority for ${REGION}.
//
// GENERATED by aws/scripts/fetch-rds-ca.sh. Do not hand-edit; re-run the script.
// Source: ${URL}
//
// WHY THIS IS A TYPESCRIPT MODULE AND NOT A FILE ON DISK.
//
// Node's bundled trust store does not contain the Amazon RDS roots, so a
// connection with \`rejectUnauthorized: true\` and no explicit \`ca\` fails against
// every RDS endpoint - and the tempting fix is \`rejectUnauthorized: false\`,
// which silently discards the only defence the open security group has.
//
// It has to reach three different bundlers intact: the Next.js standalone
// build, esbuild for the Lambda workers, and plain tsx for the offline
// harnesses. A file read with \`fs\` needs a different copy step in each. A
// string constant is just an import, so it cannot be omitted from a bundle
// without the build failing loudly.

/** The full chain, PEM. Pass as \`ssl.ca\` to node-postgres. */
export const RDS_CA_BUNDLE = \`
HDR
  cat "$PEM"
  echo '`;'
} > lib/db/rds-ca.ts

echo "==> wrote lib/db/rds-ca.ts"
